apiVersion: apps/v1
kind: Deployment
metadata:
  name: midpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midpoint
  template:
    metadata:
      labels:
        app: midpoint
    spec:
      containers:
        - image: evolveum/midpoint:4.0.2-alpine
          name: midpoint
          ports:
            - containerPort: 8080
